name: Bundle and Publish Sources
on:
  delete:
    branches:
      - '**'
      - '!main'
jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"

      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Checkout existing bundles
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: bundles

      - run: rm -rf bundles/${{ github.event.ref }}

      - name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: bundles
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}